#cloud-config

ssh_pwauth: 1

users:
  - name: {{ sysuser }} 
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    chpasswd: { expire: False }
    lock-passwd: false
chpasswd:
    list: |
        {{ sysuser }}:{{ password }}
    expire: False