#cloud-config

ssh_pwauth: 1

users:
  - name: {{ sysuser }} 
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    chpasswd: { expire: False }
    lock-passwd: false
chpasswd:
    list: |
        {{ sysuser }}:{{ password }}
    expire: False

write_files:
  - content: |
      SUBSYSTEM=="cpu", ACTION=="add", TEST=="online", ATTR{online}=="0", ATTR{online}="1"
      SUBSYSTEM=="memory", ACTION=="add", TEST=="state", ATTR{state}=="offline", ATTR{state}="online"
    path: /lib/udev/rules.d/80-hotplug-cpu-mem.rules